### ISSUE TITLE
Missing sources for C++ runtime

### ISSUE THREAD

**Issue by janvrany** [powerlang/egg#72]
`[runtime/README.md](https://github.com/powerlang/egg/tree/main/runtime#readme)` mentions "cpp" runtime for non-believers but sources are missing.

**Comment by melkyades** [comment]
I should have imagined that being a non-believer you'd check whether it was a scam :sweat_smile:. The code is in jp/cpp-vm, I just rebased it to current main, have been sleeping for a few months.

**Comment by melkyades** [comment]
the code has been merged to main now
