### ISSUE TITLE
More artefacts, please, for study before use

### ISSUE THREAD

**Issue by kdabwl** [powerlang/egg#73]
I received the first Smalltalk-80 for my back then brand new Atari Mega St on floppy disk (student copy), as executable and .image and .source; the Egg Smalltalk - a huge forward-looking and brilliant and stellar development - has only .source artifacts on Git; would it be possible to also publish at least the corresponding .image artifacts for facilitating the error-prone and mistake-prone first steps. TIA

**Comment by melkyades** [comment]
Yes, we should have artifacts automatically generated by CI in a not so far future. I'll open a branch for that.

**Comment by melkyades** [comment]
Now that I've looked, artifacts are already being generated automatically, we just haven't made a release for a long time. It's now done and READMEs document the where it is a little bit more
